apiVersion: v1
kind: ConfigMap
metadata:
  name: oms-server-configmap
  namespace: oms
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  POSTGRESQL_CONNECTION_STRING: postgresql://postgres:password@localhost:5432/users
  JWT_SECRET: "team-one"
  MONGODB_URI: "mongodb://root:password@my-mongodb-0.my-mongodb-headless:27017,my-mongodb-1.my-mongodb-headless:27017,my-mongodb-2.my-mongodb-headless:27017/database"
  POSTGRESQL_CONNECTION_STRING: "postgresql://postgres:root@my-postgresql-service:5432/users"
  PORT: "5000"
